version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5013:5013
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
