# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - 5013:5013
